-- begin FIRST_FACADE_LAYER
create unique index IDX_FIRST_FACADE_LAYER_UNIQ_IDENTIFIER on FIRST_FACADE_LAYER (IDENTIFIER) ^
-- end FIRST_FACADE_LAYER
-- begin FIRST_SINGLE_ACTOR
create unique index IDX_FIRST_SINGLE_ACTOR_UNIQ_IDENTIFIER on FIRST_SINGLE_ACTOR (IDENTIFIER) ^
-- end FIRST_SINGLE_ACTOR
