-- begin MTON_INSURANCE_MEMBERSHIP
alter table MTON_INSURANCE_MEMBERSHIP add constraint FK_MTON_INSURANCE_MEMBERSHIP_ON_PET foreign key (PET_ID) references MTON_PET(ID)^
alter table MTON_INSURANCE_MEMBERSHIP add constraint FK_MTON_INSURANCE_MEMBERSHIP_ON_INSURANCE_COMPANY foreign key (INSURANCE_COMPANY_ID) references MTON_INSURANCE_COMPANY(ID)^
create index IDX_MTON_INSURANCE_MEMBERSHIP_ON_PET on MTON_INSURANCE_MEMBERSHIP (PET_ID)^
create index IDX_MTON_INSURANCE_MEMBERSHIP_ON_INSURANCE_COMPANY on MTON_INSURANCE_MEMBERSHIP (INSURANCE_COMPANY_ID)^
-- end MTON_INSURANCE_MEMBERSHIP
