-- begin SIMI_PROPERTIES_IN_LIST
alter table SIMI_PROPERTIES_IN_LIST add constraint FK_SIMI_PROPERTIES_IN_LIST_ON_PRODUCTSET foreign key (PRODUCTSET_ID) references SIMI_PRODUCT_SET(ID)^
alter table SIMI_PROPERTIES_IN_LIST add constraint FK_SIMI_PROPERTIES_IN_LIST_ON_SINGLEACTOR foreign key (SINGLEACTOR_ID) references SIMI_SINGLE_ACTOR(ID)^
create index IDX_SIMI_PROPERTIES_IN_LIST_ON_PRODUCTSET on SIMI_PROPERTIES_IN_LIST (PRODUCTSET_ID)^
create index IDX_SIMI_PROPERTIES_IN_LIST_ON_SINGLEACTOR on SIMI_PROPERTIES_IN_LIST (SINGLEACTOR_ID)^
-- end SIMI_PROPERTIES_IN_LIST
-- begin SIMI_SINGLE_ACTOR
alter table SIMI_SINGLE_ACTOR add constraint FK_SIMI_SINGLE_ACTOR_ON_ID foreign key (ID) references SIMI_DATA_PRODUCT(ID) on delete CASCADE^
-- end SIMI_SINGLE_ACTOR
-- begin SIMI_PRODUCT_SET
alter table SIMI_PRODUCT_SET add constraint FK_SIMI_PRODUCT_SET_ON_ID foreign key (ID) references SIMI_DATA_PRODUCT(ID) on delete CASCADE^
-- end SIMI_PRODUCT_SET
-- begin SIMI_FACADE_LAYER
alter table SIMI_FACADE_LAYER add constraint FK_SIMI_FACADE_LAYER_ON_ID foreign key (ID) references SIMI_SINGLE_ACTOR(ID) on delete CASCADE^
-- end SIMI_FACADE_LAYER
-- begin SIMI_POSTGRES_DS
alter table SIMI_POSTGRES_DS add constraint FK_SIMI_POSTGRES_DS_ON_ID foreign key (ID) references SIMI_SINGLE_ACTOR(ID) on delete CASCADE^
-- end SIMI_POSTGRES_DS
